# Generated by Django 4.2.6 on 2024-04-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='costumer',
            name='style',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
