# Generated by Django 4.2.6 on 2024-04-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_costumer_address_remove_costumer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='id_number',
        ),
    ]
