# Generated by Django 4.2.6 on 2024-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_research_projects_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
