# Generated by Django 4.2.6 on 2024-07-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacher_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='biography',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
