# Generated by Django 4.2.6 on 2024-07-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_image_user_alter_teacher_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Img',
            field=models.ImageField(upload_to='dalle/'),
        ),
    ]
