# Generated by Django 4.2.6 on 2024-07-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_image_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageDallE',
        ),
    ]
