# Generated by Django 4.2.6 on 2024-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_image_imagedalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='generated/')),
                ('Type', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='ImageDallE',
        ),
    ]
